"""Join public identities to game rules, with explicit authority and coverage."""
from functools import lru_cache
import hashlib
import json
from pathlib import Path
import re


@lru_cache(maxsize=8)
def bundle(root: str):
    path = Path(root) / 'rule-evidence.json'
    return json.loads(path.read_text()) if path.exists() else {}


@lru_cache(maxsize=8)
def index(root: str):
    result = {}
    for kind in ('cards', 'enemies', 'relics', 'potions'):
        path = Path(root) / (kind + '.jsonl')
        if not path.exists():
            continue
        for line_number, line in enumerate(path.open(encoding='utf-8'), 1):
            row = json.loads(line)
            result[kind, row['id']] = (row, str(path.resolve()), line_number)
    for row in bundle(root).get('entities', []):
        result[row['kind'], row['id']] = (row, str(Path(root)/'rule-evidence.json'), None)
    return result


def authority(state, root):
    path = Path(root) / 'manifest.json'
    if not path.exists():
        return {'status': 'unverified', 'reason': 'knowledge_manifest_missing'}
    manifest = json.loads(path.read_text())
    expected = {'game_version': manifest['game_version'].lstrip('v'),
                'game_commit': manifest['game_commit'],
                'game_assembly_sha256': manifest['sources']['assembly']['sha256']}
    actual = dict(state.get('rules_context') or {})
    actual['game_version'] = str(actual.get('game_version') or '').lstrip('v')
    missing = [k for k in expected if not actual.get(k)]
    mismatches = [k for k, v in expected.items() if actual.get(k) and actual[k] != v]
    evidence = bundle(str(Path(root).resolve()))
    if not evidence:
        missing.append('rule_evidence')
    elif evidence.get('assembly_sha256') != expected['game_assembly_sha256']:
        mismatches.append('rule_evidence.assembly_sha256')
    return {'status': 'mismatch' if mismatches else 'unverified' if missing else 'verified',
            'expected': expected, 'actual': actual, 'missing': missing, 'mismatches': mismatches,
            'scope': 'base_game_assembly_match; gameplay_mod_overrides_require_separate_review'}


def require_authority(state, root):
    result = authority(state, root)
    if result['status'] != 'verified':
        raise ValueError('Rules source is not verified: ' + json.dumps(result, ensure_ascii=False))
    return result


def visible_knowledge(state, root):
    root = str(Path(root).resolve())
    lookup, evidence = index(root), bundle(root)
    crosscheck_file = Path(root) / 'community-crosschecks.json'
    crosschecks = json.loads(crosscheck_file.read_text()).get('models', {}) if crosscheck_file.exists() else {}
    identities, active = set(), set()

    def add(kind, value, relevant=True):
        if value:
            key = (kind, str(value).split('.')[-1])
            identities.add(key)
            if relevant: active.add(key)

    def card(c, relevant=True):
        if not isinstance(c, dict): return
        add('cards', c.get('id') or c.get('card_id'), relevant)
        for field, kind in [('enchantment', 'enchantments'), ('affliction', 'afflictions')]:
            item = c.get(field) or {}
            add(kind, item.get('id') or item.get('model_id'), relevant)

    def statuses(actor):
        for power in actor.get('status', []):
            add('powers', power.get('id') or power.get('model_id'))

    player = state.get('player', {})
    for field in ('hand', 'deck', 'draw_pile', 'discard_pile', 'exhaust_pile'):
        for c in player.get(field, []): card(c, field == 'hand')
    statuses(player)
    for kind in ('relics', 'potions'):
        for item in player.get(kind, []): add(kind, item.get('id'))
    battle = state.get('battle', {})
    for enemy in battle.get('enemies', []) + battle.get('inactive_enemies', []):
        add('enemies', enemy.get('id') or str(enemy.get('entity_id', '')).rsplit('_', 1)[0])
        statuses(enemy)
    for block in ('card_reward', 'card_select', 'hand_select'):
        for c in state.get(block, {}).get('cards', []): card(c)
    for block in (state.get('shop', {}), state.get('rewards', {})):
        for item in block.get('items', []):
            card(item)
            for key, kind in [('relic_id', 'relics'), ('potion_id', 'potions')]: add(kind, item.get(key))

    # Resolve public rule dependencies: the monster's death power, a card's
    # applied debuff, and cards generated by a visible power.
    class_index = {Path(row.get('source', {}).get('decompiled_path', '')).stem: key
                   for key, (row, _, _) in lookup.items()}
    queue, visited, source_errors = list(active), set(), []
    while queue:
        key = queue.pop()
        if key in visited or key not in lookup: continue
        visited.add(key)
        row = lookup[key][0]
        source = row.get('source', {})
        relative, base = source.get('decompiled_path'), evidence.get('decompiled_root')
        code = source.get('rule_source', '')
        if relative and base:
            path = Path(root) / base / relative
            if not path.exists() or hashlib.sha256(path.read_bytes()).hexdigest() != source.get('sha256'):
                source_errors.append({'kind': key[0], 'id': key[1], 'reason': 'local_source_missing_or_changed'})
                continue
            code = path.read_text()
        types = set(re.findall(r'\b(?:ModelDb\.(?:Card|Power|Monster|Enchantment|Affliction)|[A-Z]\w*Cmd\.\w+)<(\w+)', code))
        for name in types:
            if name in class_index:
                dep = class_index[name]
                identities.add(dep); active.add(dep); queue.append(dep)

    references, facts, missing = [], [], []
    for kind, identity in sorted(identities):
        match = lookup.get((kind, identity))
        if match is None:
            missing.append({'kind': kind, 'id': identity})
            continue
        row, path, line = match
        source = row.get('source', {})
        ref = {'kind': kind, 'id': identity, 'model_id': row.get('model_id'),
               'game_version': row.get('game_version'), 'path': path, 'line': line,
               'source_sha256': source.get('sha256'), 'decompiled_path': source.get('decompiled_path'),
               'evidence': 'versioned_game_rules'}
        references.append(ref)
        facts.append({**ref, 'runtime': row.get('runtime', {}), 'localized': row.get('localized', {}).get('zhs', {}),
                      'community_crosschecks': crosschecks.get(row.get('model_id'), []),
                      **{k: source[k] for k in ('mechanic_lines', 'numeric_expressions', 'move_state_machine_source', 'rule_source') if k in source}})
    models = {f['model_id'] for f in facts if (f['kind'], f['id']) in active}
    checks = [c for c in evidence.get('checks', []) if not c['related_models'] or models.intersection(c['related_models'])]
    for check in checks:
        for ref in check['sources']:
            path = Path(root) / evidence['decompiled_root'] / ref['decompiled_path']
            if not path.exists() or hashlib.sha256(path.read_bytes()).hexdigest() != ref['sha256']:
                source_errors.append({'check': check['id'], 'reason': 'local_source_missing_or_changed'})
    trust = authority(state, root)
    if source_errors:
        trust = {**trust, 'status': 'mismatch', 'source_errors': source_errors}
    return {'references': references, 'facts': facts, 'missing': missing, 'authority': trust,
            'decision_context': {
                'authority': trust, 'rules': checks,
                'active_facts': [f for f in facts if (f['kind'], f['id']) in active],
                'coverage': 'Versioned source retrieval and six reviewed checks; not a complete rule interpreter.',
                'priority': 'Current engine card/status text and supported previews first. Never apply base values on top of an already modified preview. Missing/unsupported effects require reading cited source before acting.'}}
